### ISSUE TITLE
ReverseStep Bug

### ISSUE THREAD

**Issue by WoodyLetsPlay** [CCBlueX/liquidbounce.tk#4]
Der Longjump zieht manchmal richtig schnell nach unten, wenn man ReverseStep an hat.

**Comment by Marco-MC** [comment]
Ähm, hier soll man keine Issues reporten sondern unter LiquidBounce1.8-Issues...
Hab auf jedenfall schon nen Issue erstellt: https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/162
